# Load
. /opt/homebrew/opt/asdf/libexec/asdf.sh
eval "$(rbenv init - --no-rehash zsh)"

# Telling Git about my GPG key
export GPG_TTY=$(tty)

# Added by OrbStack: command-line tools and integration
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
